Feature: CiviMail tokens for tax deductible contributions.

Scenario: Sending an email to a contact with contributions

When an email with the tokens contributions.total and contributions.itemized is sent to a contact
And that contact has a contribution with a receive date between 1/1/<lastYear> and 1/1/<thisYear>
And that contribution is of a type that is tax deductible
Then that contribution will be included in the contributions.total
And a line item for that contribution will be included in the table generated by the contributions.itemized
